TortoiseGitPLink: Fix compilation in debug configuration
...\src\tortoiseplink\ssh.c(1216): error C2051: case expression not constant

Line 421 of ssh.c says:

 * In particular, if you are getting `case expression not constant'
 * errors when building with MS Visual Studio, this is because MS's
 * Edit and Continue debugging feature causes their compiler to
 * violate ANSI C. To disable Edit and Continue debugging:
 *
 *  - right-click ssh.c in the FileView
 *  - click Settings
 *  - select the C/C++ tab and the General category
 *  - under `Debug info:', select anything _other_ than `Program
 *    Database for Edit and Continue'.

Signed-off-by: Jano Svitok <jsv@whitestein.com>
Signed-off-by: Sven Strickroth <email@cs-ware.de>