Fix compilation
...\ext\gitdlltest\gitdlltest.cpp(77): error C2660: 'git_get_log_nextcommit' : function does not take 2 arguments

- add missing parameter (0 - I assume that --follow is not needed for this test)
- add documentation for the new parameter (I'm not sure if I guessed it properly)

Signed-off-by: Jano Svitok <jsv@whitestein.com>