Fix compilation
32>------ Build started: Project: Cache, Configuration: Debug Win32 ------
32>  TGitPath.cpp
...
32>...\src\git\tgitpath.cpp(1288): error C2039: 'mem_fun_ref' : is not a member of 'std'
32>...\src\git\tgitpath.cpp(1288): error C3861: 'mem_fun_ref': identifier not found

- add required #include

Signed-off-by: Jano Svitok <jsv@whitestein.com>