Fix compilation
29>  GitIndexTest.cpp
29> ...\src\git\gitindex.h(58): error C2039: 'shared_ptr' : is not a member of 'std::tr1'

- add require include

Signed-off-by: Jano Svitok <jsv@whitestein.com>