Fix compilation
...\test\gitindextest\gitindextest.cpp(24): fatal error C1083: Cannot open include file: 'gitstatus.h': No such file or directory

- add required include directories to the project file.

Note that project has win32 configurations only - maybe x64 should be added as well.

Signed-off-by: Jano Svitok <jsv@whitestein.com>